url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "speakingofdata" # the name of your site, e.g. ACME Corp.
description: "speech processing&ensp;—&ensp;ethical data science&ensp;—&ensp;assistive technology"
