menu:
- {name: 'home', url: '/'}
- {name: 'about', url: '/about'}
- {name: 'portfolio', url: '/portfolio'}
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/Strickland_CV.pdf'}

social:
- {style: 'fa-solid', icon: 'envelope', link: 'mailto:speakingofdata@gmail.com', text: 'speakingofdata@gmail.com'}
- {style: 'fab', icon: 'github', link: 'https://github.com/speakingofdata', text: 'github.com/speakingofdata'}
- {style: 'fab', icon: 'linkedin', link: 'https://www.linkedin.com/in/speakingofdata/', text: 'linkedin.com/in/speakingofdata'}
- {style: 'fa-solid', icon: 'mortar-board', link: 'https://www.semanticscholar.org/author/Harper-Strickland/2327050896', text: 'semanticscholar.org: Harper Strickland'}
